micronaut:
  application:
    name: micronautCasaDoCodigo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/micronaut_casa_do_codigo?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'root'
jpa.default.properties.hibernate.hbm2ddl.auto: create-drop
